// examples/vue/src/components/LitDemo.vue
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue';
import type { Dialog } from '@lit-ui/dialog';

const count = ref(0);
const dialogOpen = ref(false);
const dialogRef = ref<Dialog | null>(null);

// Handle dialog open/close through the DOM element
watch(dialogOpen, (isOpen) => {
  const dialog = dialogRef.value;
  if (!dialog) return;

  if (isOpen) {
    dialog.show();
  } else {
    dialog.close();
  }
});

// Listen for dialog close event
onMounted(() => {
  const dialog = dialogRef.value;
  if (!dialog) return;

  const handleClose = () => {
    dialogOpen.value = false;
  };
  dialog.addEventListener('close', handleClose);

  onUnmounted(() => {
    dialog.removeEventListener('close', handleClose);
  });
});
</script>

<template>
  <div class="demo" :style="{ '--lui-button-radius': '8px' }">
    <div class="button-row">
      <lui-button variant="primary" @click="count++">
        Clicked {{ count }} times
      </lui-button>

      <lui-button variant="secondary" @click="dialogOpen = true">
        Open Dialog
      </lui-button>
    </div>

    <lui-dialog ref="dialogRef">
      <span slot="title">Hello from Lit UI</span>
      <p>This dialog is a Lit component rendered in Vue.</p>
      <p>The showModal/close APIs work correctly with Vue reactivity.</p>
      <div slot="footer" class="dialog-footer">
        <lui-button variant="secondary" @click="dialogOpen = false">
          Close
        </lui-button>
        <lui-button variant="primary" @click="dialogOpen = false">
          Confirm
        </lui-button>
      </div>
    </lui-dialog>
  </div>
</template>

<style scoped>
.button-row {
  display: flex;
  gap: 1rem;
  align-items: center;
  margin-bottom: 1rem;
}

.dialog-footer {
  display: flex;
  gap: 0.5rem;
  justify-content: flex-end;
}
</style>

// examples/svelte/src/lib/components/LitDemo.svelte
<script lang="ts">
  import type { Dialog } from '@lit-ui/dialog';

  let count = $state(0);
  let dialogOpen = $state(false);
  let dialogRef: Dialog | undefined = $state();

  // Handle dialog open/close through the DOM element
  $effect(() => {
    const dialog = dialogRef;
    if (!dialog) return;

    if (dialogOpen) {
      dialog.show();
    } else {
      dialog.close();
    }
  });

  function handleDialogClose() {
    dialogOpen = false;
  }
</script>

<div class="demo" style="--lui-button-radius: 8px;">
  <div class="button-row">
    <lui-button variant="primary" onclick={() => count++}>
      Clicked {count} times
    </lui-button>

    <lui-button variant="secondary" onclick={() => (dialogOpen = true)}>
      Open Dialog
    </lui-button>
  </div>

  <lui-dialog bind:this={dialogRef} onclose={handleDialogClose}>
    <span slot="title">Hello from Lit UI</span>
    <p>This dialog is a Lit component rendered in Svelte.</p>
    <p>The showModal/close APIs work correctly with Svelte 5 runes.</p>
    <div slot="footer" class="dialog-footer">
      <lui-button variant="secondary" onclick={() => (dialogOpen = false)}>
        Close
      </lui-button>
      <lui-button variant="primary" onclick={() => (dialogOpen = false)}>
        Confirm
      </lui-button>
    </div>
  </lui-dialog>
</div>

<style>
  .button-row {
    display: flex;
    gap: 1rem;
    align-items: center;
    margin-bottom: 1rem;
  }

  .dialog-footer {
    display: flex;
    gap: 0.5rem;
    justify-content: flex-end;
  }
</style>
